### ISSUE TITLE
Separating self learning resources into a new section

### ISSUE THREAD

**Issue by yahia3200** [EssamWisam/cmp-docs#1]
As always great work MR.Essam ❤️️❤️️

I would suggest having a separate "Self-Learning Resources" section instead of nesting it in the "Recently Joined" one for example:

Self-Learning Resources
├── Machine Learning
├── Software Engineering
└── Embedded Systems

This is because this more easier to find and I think this section will have a lot of valuable resources for each field.

**Comment by EssamWisam** [comment]
Delighted to hear you feedback, Mr. Yehia 💖💖💖. I think my rationale when I did that was that this section would include courses that recently joined students can cover in this summer vacation (e.g., CS50 and such). However, I completely concur that doing it in the way you proposed is more general, maybe we can also have an entry for "Computer Science Principles" that will have content students can go through before their first year. What do you think?

**Comment by yahia3200** [comment]
Agree with you, closing and will start working on it
