### ISSUE TITLE
🗣️ Translate "Recently Joined" Section

### ISSUE THREAD

**Issue by EssamWisam** [EssamWisam/cmp-docs#15]
Most of the website is already translated, except for some pages in the "Recently Joined" section. Translation should ideally be in Egyptian Arabic.

To be translated:
- [ ] Choosing a Laptop
- [ ] Self-learning Resources
- [x] Representative & Teams Page
- [x] Communication Channels Page
- [x] Google Drive Page

Relevant files can be found in `public/department/General/Recently`. Each `x.yaml` file is in English and should have a corresponding `x_ar.yaml` file in Arabic.

**Comment by Iten-No-404** [comment]
If you haven't already started on this, I can do it.😁

**Comment by EssamWisam** [comment]
> If you haven't already started on this, I can do it.😁

I genuinely appreciate your willingness to assist, Iten. No, I am not working on it. Besides of assigning this to yourself using the right corner, do mention if you will only work on only specific pages in another comment (assuming it's not all the pages).

Thanks a lot.

**Comment by Iten-No-404** [comment]
> do mention if you will only work on only specific pages in another comment

I can work on all of them, since most of the work will go to `Representative & Teams Page` and `Communication Channels Page`. The rest don't have much content yet.
