### ISSUE TITLE
`npm start` does not work correctly for Linux.

### ISSUE THREAD

**Issue by KnockerPulsar** [EssamWisam/cmp-docs#21]
Currently, running `npm start` reports the following error:
```
node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

A quick google reveals that this issue can be fixed by omitting the `export`, this will do the same as calling  `export`, the command, then `unset`. So just: `NODE_OPTIONS=--openssl-legacy-provider && react-scripts start` should work.

Another thing, not sure if this is a copy-paste error, but I think the `SET` command was meant just for windows?

**Comment by Iten-No-404** [comment]
@KnockerPulsar , did you try running using `npm run start_win` and it didn't work?
For Windows, I always use it. I am not sure what Essam is using but it's probably MacOS. 
You can just add a new entry in the scripts and call it `start_lin` or something and write the command that you just mentioned.

**Comment by Iten-No-404** [comment]
@EssamWisam , I'll close this issue as well since it's resolved properly.
