### ISSUE TITLE
🖼 Invalid Image Links Bug Fix

### ISSUE THREAD

**Issue by Iten-No-404** [EssamWisam/cmp-docs#24]
![Issue 23](https://github.com/EssamWisam/cmp-docs/assets/56697800/56053493-d81c-4f91-b40c-61f4e3e2e5f1)
As can be seen in the image above, the links to profile pictures in LinkedIn are subject to constant change and so, the links should be checked for validity before they are displayed in the website.

**Comment by EssamWisam** [comment]
Saw this earlier and thought it was browser dependent. I have Edge and Safari and on Safari, the images would not appear to be squished.

Nonetheless, this is an ideal solution to the problem. I tried to see if there is an automatic way to have them updated but LinkedIn's API does not give access to profile pictures.

Thanks.

**Comment by Iten-No-404** [comment]
> on Safari, the images would not appear to be squished.

Interesting.
> if there is an automatic way to have them updated

There must be a way somehow. If I find one, I'll be sure to do a PR.
> Thanks.

You're welcome.

**Comment by EssamWisam** [comment]
> There must be a way somehow. If I find one, I'll be sure to do a PR.

I assure you that according to my research, there isn't. It requires being logged in to the account holding the profile picture.
