### ISSUE TITLE
Consider rewriting the LinkedIn script with `linkedin-api`

### ISSUE THREAD

**Issue by EssamWisam** [EssamWisam/cmp-docs#78]
### Problem Statement:
Run script is quite tedious. I tried to do it once and was unhappy with how long it was taking or the warnings being printed. @Iten-No-404 thankfully has invested periodic effort to run the script.

### Proposed Solution:
Looking over [their docs](https://linkedin-api.readthedocs.io/en/latest/api.html) they have:
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/79ad9749-0823-4655-93fd-40a10b2060e4">
and
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/ef52d6ae-470f-434a-b3e3-daa940218b8a">
and
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/69cb9375-2af9-43fa-92c9-6ddeee4df940">

I have used this package before in a very different application (e.g., getting comments on a specific post) and with a little hack alhamdulilah was able to make it run via a Github action. I think the package is quite straightforward to use.

If @KnockerPulsar or @Iten-No-404 or someone else has time (i), test these functions to ascertain that this is inshAllah feasible and (ii), write a script using them to replace the current one (the new script inshAllah should be just few lines of code) then I can inshAllah try to do (iii), wrap it in a Github action to make it run periodically.

**Comment by Iten-No-404** [comment]
Interesting. I took a quick look at their documentation and it seems that they use HTTP requests directly instead of using Selenium which should save running time.

However, I think we may still face the same issue of verification when using GitHub actions since the IP address of the machine that's going to run the script will definitely be a new IP address that hasn't been associated with the account before.
Have you tried using this package with GitHub actions before? 🤔

Either way, I can take a look at the package and try it out. Decreasing the execution time would still be quite beneficial.

**Comment by EssamWisam** [comment]
> Have you tried using this package with GitHub actions before? 🤔

Yes, I thought I mentioned in the original post that I did but it required a little hack. Basically, I ported my local browser cookies into Github and it worked. There is one caveat: if I ever log out from browser then cookies expire but that's easy to handle by simply downloading a new browser lol...

**Comment by Iten-No-404** [comment]
Sorry, seems like I missed that line. 😂
I get what you mean. Downloading any lightweight browser should be quite simple and sufficient. 
I'll try out the package today or tomorrow insha'allah, and inform you of my findings.

**Comment by EssamWisam** [comment]
I sincerely thank you in advance for your proactivity.

**Comment by Iten-No-404** [comment]
@EssamWisam, I have tried the package out and it's great! It contains all the information we need and much more. It is definitely much faster than Selenium and it will enable us to use or display much more data if we want to. I have started working on the new script. It should be finished by the end of the week insha'allah. That way we can configure the GitHub action for it to run automatically soon.
Thank you for taking the initiative on this.

**Comment by EssamWisam** [comment]
Sounds fantastic. I think for the skills just get all skills and take top four.

**Comment by Iten-No-404** [comment]
> I think for the skills just get all skills and take top four. 
The skills are received sorted alphabetically so taking the top 4 won't be the most informative but we can take the skills like that for now.

**Comment by EssamWisam** [comment]
> > I think for the skills just get all skills and take top four.
> 
> The skills are received sorted alphabetically so taking the top 4 won't be the most informative but we can take the skills like that for now.

I imagined it would sort based on number of endorsements which would make sense but alright I think we can just ignore it then or take top five alphabetically and see if it makes sense perhaps, a random sample of five skills would make more sense or ignoring.

**Comment by Iten-No-404** [comment]
Good afternoon @EssamWisam, I am almost done with the script but I want your opinion on something. Since we are able to easily and accurately get the list of experiences for each student, should we make more use of it? 

In the old script, the current position was extracted in this format: `{position_name}, {company_name} · {work_mode}, {start_month_year} - Present · X yr Y mos` (LinkedIn's display format) which is fine. However, it only takes into account the newest current position. Using this new script, it can be easily changed to capture all current positions which would be more informative. What do you think?

**Comment by EssamWisam** [comment]
Good afternoon.

While I think it's valuable, I think it could be left as future work. In particular, the value of seeing the ksot recent position so far carries more weight in terms of the main objective of the feature.

In the future, I think this can of too much value (as well as extracting other things). I want us to have a statistics portal that collects many statistics from all the years (but this is future work).

Thank you a lot for the work that you have done.

**Comment by Iten-No-404** [comment]
> While I think it's valuable, I think it could be left as future work.

Sure thing.

> In the future, I think this can of too much value (as well as extracting other things). I want us to have a statistics portal that collects many statistics from all the years (but this is future work).

Yes, I have also thought about this. There are lot of statistics that can be done on the data we have, for example: the number & percentage of students per class that work in company A (and the overall count & percentage for such company), the percentage of currently unemployed students per class and in total, job-hopping rates, and so on... This could be further discussed later on.

> Thank you a lot for the work that you have done.

You're very welcome.
